In [1]:
import pandas as pd

In [15]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [16]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [17]:
#Text processing - 1 converting into lowercase
df["review"] = df["review"].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [18]:
# 2 - removing URLs
import re
def remove_url(text):
    text =re.sub("http/S+","",text) #(pattern , repl , string)
    return text
    
df["review"] = df["review"].apply(remove_url)

In [19]:
# remove punctuation
def remove_punct(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
df["review"]= df["review"].apply(remove_punct)

In [20]:
# remove html tags 
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text
df["review"]  = df["review"].apply(remove_html)
df.sample(10)

                                                  review sentiment
154    i dont think ive ever gave something a 110 rat...  negative
49251  when i saw alien vs predator a few years ago i...  negative
42555  a conversation about how janmichael vincent is...  negative
21776  turkish culture is complete with lots of diffe...  positive
41602  from hardly alien sounding lasers to an elemen...  negative
31822  for his last film john huston directed his dau...  positive
12946  this film is a true and historical film it is ...  positive
37318  yes i couldnt stop yawning nor could my partne...  negative
9063   i thoroughly enjoyed the first part of this tw...  positive
21069  ive received this movie from a cousin in norwa...  positive