In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
#Text processing - 1 converting into lowercase
df["review"] = df["review"].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [5]:
# 2 - removing URLs
import re
def remove_url(text):
    text =re.sub("http/S+","",text) #(pattern , repl , string)
    return text
    
df["review"] = df["review"].apply(remove_url)

In [6]:
# remove punctuation
def remove_punct(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
df["review"]= df["review"].apply(remove_punct)

In [7]:
# remove html tags 
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text
df["review"]  = df["review"].apply(remove_html)
df.sample(10)

                                                  review sentiment
48077  never when i was a child did i love any movie ...  positive
34613  many of the american people would saywhat to m...  positive
43471  the plot of  astronuat returns to earth as a m...  negative
4      petter matteis love in the time of money is a ...  positive
11225  i have grown up reading modesty blaise both th...  negative
4843   time and time again ive stated that if people ...  positive
32700  white man  progress  industrialization  bad fi...  positive
29836  this movie was terrible the acting was awful t...  negative
10385  if i could give this movie less than a 1 i wou...  negative
45886  a couple of men are shipwrecked on a remote is...  negative

In [9]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [11]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
# remove stop words 

def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word,"")
    return text

In [12]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive