In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("IMDB Dataset.csv")
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [3]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [4]:
#Text processing - 1 converting into lowercase
df["review"] = df["review"].str.lower()
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. <br /><br />the...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [5]:
# 2 - removing URLs
import re
def remove_url(text):
    text =re.sub("http/S+","",text) #(pattern , repl , string)
    return text
    
df["review"] = df["review"].apply(remove_url)

In [6]:
# remove punctuation
def remove_punct(text):
    text = re.sub(r"[^A-Za-z0-9\s]","",text)
    return text
df["review"]= df["review"].apply(remove_punct)

In [7]:
# remove html tags 
def remove_html(text):
    text = re.sub(r"<.*?>","",text)
    return text
df["review"]  = df["review"].apply(remove_html)
df.sample(10)

                                                  review sentiment
3135   i dont know what the oscar voters saw in this ...  negative
36011  this movie includes one of the best characters...  positive
20537  i saw this on sale  new  at my local store for...  negative
27929  i havent seen so many people packed outside a ...  positive
6798   yesa real stinker i saw this movie on the advi...  negative
5115   normally when i go on a raid of the local holl...  negative
26727  it was the first action movie made in banned i...  negative
8619   this is indeed a treat for every bolan fan som...  positive
19606  this movie is fun to watch if you liked dave w...  positive
4655   this movie pretty much surprised me i didnt ha...  positive

In [8]:
import nltk
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to C:\Users\Murli
[nltk_data]     Bhatt\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [9]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
# remove stop words 

def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word,"")
    return text

In [10]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production br br the filmin...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [15]:
# Stemming 
from nltk.stem import PorterStemmer

def stemming(text):
    ps = PorterStemmer()
    stemmed_words= []

    tokens = word_tokenize(text)

    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return "".join(stemmed_words)
df["review"] = df["review"].apply(stemming)
df.head()

                                              review sentiment
0  oneoftheotherreviewhamentionthatafterwatchjust...  positive
1  awonderlittlproductbrbrthefilmtechniquisveriun...  positive
2  ithoughtthiwaawonderwaytospendtimeonatoohotsum...  positive
3  basicthereafamiliwherealittlboyjakethinktherea...  negative
4  pettermatteiloveinthetimeofmoneyisavisualstunf...  positive

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df["sentiment"] = le.fit_transform(df["sentiment"])

y = df["sentiment"]
y.head()

0    1
1    1
2    1
3    0
4    1
Name: sentiment, dtype: int64

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features = 5000)

X = tfidf.fit_transform(df["review"])

In [22]:
from sklearn.model_selection import train_test_split

x_train , x_test , y_train , y_test =  train_test_split(X,y,test_size = 0.2,random_state=42)

x_train.shape

(40000, 5000)